name: Tests for Plugin Environmental Data Retrival

on:
  push:
    paths:
    - "edr_plugin/**"
    - ".github/workflows/test_plugin.yaml"
    - "tests/**"

jobs:

  Tests-plugin-Environmental-Data-Retrival:

    runs-on: ubuntu-latest

    steps:

      - name: Install QGIS
        run: |
          sudo wget -qO /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] https://qgis.org/ubuntu `lsb_release -c -s` main" > /etc/apt/sources.list.d/qgis.list'
          sudo apt-get update
          sudo apt-get install -y qgis
            
      - name: Install Python packages
        run: pip install pytest pytest-qgis

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=/usr/share/qgis/python/plugins:/usr/share/qgis/python:." >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          QT_QPA_PLATFORM=offscreen pytest tests -rP -vv -s